# @baseUrl = http://localhost:3000
@baseUrl = https://coruscating-sable-0b4705.netlify.app
@todoUrl = {{baseUrl}}/api/todos

###

GET   {{todoUrl}}  HTTP/1.1

###

POST  {{todoUrl}}  HTTP/1.1
content-type: application/json

{
  "name": "Ahaha"
}

###

PUT   {{todoUrl}}   HTTP/1.1
content-type: application/json

{
  "id": "111",
  "name": "Update Todo 111"
}

###

DELETE  {{todoUrl}} HTTP/1.1
content-type: application/json

{
  "id": "111"
}

